version: '3.8'

services:
  web:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_IP=${SERVER_IP}
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - db
      - migrations
    volumes:
      - .:/app
    command: uvicorn app.main:app --host ${SERVER_IP} --port ${SERVER_PORT}

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: bash -c "sleep 5 && alembic upgrade head"

volumes:
  postgres_data: